export class User {
  user_Id:any
  firstName:any
  lastName:any
  dateNaissance:any
  phone:any
  email:any
  password:any
  cin:any
  adresse:any
  sexe:any
  image:any
  alumni:any
  enabled:any
  roles:any
  postSet:any
  candidacySet:any
  commentSet:any
  blogSet:any
  reportSet:any
  userFavOffers:any
  userLikes:any
  userDislikes:any
  reponseReports:any
  universities:any
}
